"""Original API learning path: explain, predict, practice, then check."""
MDN='https://developer.mozilla.org/en-US/docs/'
INTRO=MDN+'Learn_web_development/Extensions/Client-side_APIs/Introduction'
THIRD=MDN+'Learn_web_development/Extensions/Client-side_APIs/Third_party_APIs'
FETCH=MDN+'Web/API/Fetch_API/Using_Fetch'
DESIGN='https://github.com/microsoft/api-guidelines/blob/a7022a299442a8352431874e63ec4dff548a1b81/azure/ConsiderationsForServiceDesign.md'
GUIDE='https://github.com/microsoft/api-guidelines/blob/a7022a299442a8352431874e63ec4dff548a1b81/azure/Guidelines.md'
OAS='https://spec.openapis.org/oas/v3.1.2.html'
SEC='https://owasp.org/API-Security/editions/2023/en/'
POSTMAN='https://learning.postman.com/docs/tests-and-scripts/write-scripts/test-scripts/'
RFC9457='https://www.rfc-editor.org/rfc/rfc9457.html'
RFC9700='https://www.rfc-editor.org/rfc/rfc9700.html'
EXTERNAL_SOURCES=[
 dict(title='Postman: write response tests',url=POSTMAN,summary='Use named post-response assertions on status, headers and returned data. Request-level checks can cover one operation; collection/folder scripts can share checks. The supplied collection includes original examples using pm.test and pm.expect.'),
 dict(title='Postman: variables and environments',url='https://learning.postman.com/docs/use/send-requests/variables/variables/',summary='Parameterize the base URL and demo credentials, rather than changing every request. Choose a variable scope deliberately and keep real secrets out of shared exports. The supplied collection uses local teaching tokens only.'),
 dict(title='Postman: run a collection',url='https://learning.postman.com/docs/tests-and-scripts/running-collections/intro-to-collection-runs/',summary='Run requests in a reproducible order and inspect their assertion results. A response can save an ID or validator for the next request. Use an isolated fixture and deliberate setup/cleanup rather than relying on yesterday’s server state.'),
 dict(title='Swagger: OpenAPI and documentation tools',url='https://swagger.io/docs/specification/v3_0/about/',summary='OpenAPI is the description format; Swagger supplies tools such as editors, documentation renderers and generators. A generated UI or SDK does not establish authorization or business correctness. This linked guide uses OpenAPI 3.0; this course’s contract examples use 3.1.'),
 dict(title='RFC 9457: Problem Details',url=RFC9457,summary='Problem Details gives HTTP APIs a reusable error representation. Type identifies the kind of problem; title/detail help people; status agrees with the origin’s HTTP response. Extensions can carry safe validation details. Never expose implementation secrets in error payloads.'),
 dict(title='RFC 9700: OAuth 2.0 security guidance',url=RFC9700,summary='Read this current security guidance alongside the OAuth framework. Authorization code with PKCE is an important modern pattern; avoid treating legacy implicit/password examples as a default. Follow the identity provider’s validated flow and token-handling guidance.'),
 dict(title='GraphQL: learning guide',url='https://graphql.org/learn/',summary='GraphQL specifies a typed schema and query execution model. Learn how a client selects fields and how servers resolve them; HTTP transport alone does not define those operations. Continue in the separate graphql-lms for depth.'),
 dict(title='gRPC: introduction',url='https://grpc.io/docs/what-is-grpc/introduction/',summary='gRPC defines services and remote calls, commonly using Protocol Buffers and generated stubs. It supports unary and streaming call patterns. Choose it according to client/runtime needs, not merely because a payload is smaller.'),
]
TOPIC_MAP=[
 ('API concepts and protocol choices',['api-model','protocols','read-contract']),
 ('Consuming third-party APIs',['consume','browser-boundaries','sdk-client']),
 ('Resource and operation design',['resources','operations','data-contract','pagination','errors']),
 ('Authentication and authorization',['credentials','oauth','authorization']),
 ('All OWASP API Security Top 10 2023 risks',['validation','threats']),
 ('OpenAPI contracts and documentation',['openapi','schema-models','refs-security','documentation']),
 ('Postman and layered API testing',['postman','test-layers','negative-tests']),
 ('Reliable integrations',['retry','concurrency','async-webhooks','streams']),
 ('Lifecycle and operations',['versioning','observability','capstone']),
]

def source_label(url):
    labels={INTRO:'MDN: Introduction to web APIs',THIRD:'MDN: Third-party APIs',FETCH:'MDN: Using Fetch',DESIGN:'Microsoft: Service design',GUIDE:'Microsoft: REST API guidelines',OAS:'OpenAPI 3.1.2 specification',RFC9457:'RFC 9457: Problem Details',RFC9700:'RFC 9700: OAuth security',POSTMAN:'Postman: Write response tests'}
    if url in labels:return labels[url]
    if url.startswith(SEC):return 'OWASP: '+url.rstrip('/').split('/')[-1].split('-',1)[-1].replace('-',' ').capitalize()
    if 'developer.mozilla.org' in url:return 'MDN: '+url.rstrip('/').split('/')[-1].replace('_',' ')
    if 'learning.postman.com' in url:return 'Postman: '+url.rstrip('/').split('/')[-1].replace('-',' ')
    if 'swagger.io' in url:return 'Swagger: OpenAPI overview'
    if 'graphql.org' in url:return 'GraphQL learning guide'
    if 'grpc.io' in url:return 'gRPC introduction'
    if 'VersioningGuidelines' in url:return 'Microsoft: Versioning guidelines'
    return 'API reference'

def D(id,title,goal,topics,exercise,answer,sources):
    slides=[('Goal and reading',goal+'\n\n'+'\n\n'.join('['+source_label(url)+']('+url+')' for url in sources))]+topics+[('Practice — predict before trying',exercise),('Worked self-check',answer)]
    return dict(id=id,type='slides',title=title,slides=[dict(id=f'{id}-s{i+1}',title=t,body=b) for i,(t,b) in enumerate(slides)])
def Q(id,title,skill,questions):
    return dict(id=id,type='quiz',title=title,skill=skill,questions=[dict(id=f'{id}-q{i+1}',prompt=p,options=o,answer=a,explanation=e) for i,(p,o,a,e) in enumerate(questions)])
def S(id,title,lessons,questions,skill):return dict(id=id,type='section',title=title,children=lessons+[Q(id+'-quiz','Skill check — '+skill,skill,questions)])

def make_course():
    start=D('start','Start here','Learn to consume, design, describe and test an API.',[
      ('Your course sequence','Study JSON → HTTP → API → GraphQL. Use the separate JSON and HTTP courses for syntax and transport details; short reminders here keep the focus on the API contract. No HTTP packet catalog or full browser API catalog is required.'),
      ('Two useful layers','The guided path contains original explanations, exercises and skill checks. The optional reference collection includes the complete text of the explicitly selected licensed MDN, Microsoft, OpenAPI and OWASP documents, plus linked tool/standards reading guides. It does not claim to include every API document on those websites.'),
      ('How to work','Predict an outcome, run the local request, then compare with the worked answer. Exercises are self-assessed; quizzes provide immediate feedback, allow retakes and pass at 80%. Notes, progress and reports live in this browser. Correct answers are bundled with the static reader.'),
      ('Local practice','Run node scripts/practice-server.cjs, then open http://localhost:8000. The synthetic Tasks API uses demo-alice, demo-bob and demo-readonly as teaching bearer tokens. These are public labels, not real identity credentials. State is memory-only and resets on restart. Read practice/README.md for the complete workflow.')],
      'Choose a task you want a program to accomplish. State its input, output and one failure case.',
      'A useful API contract describes what a caller can ask for, what it receives and the conditions under which the operation succeeds. A URL alone is insufficient.',[INTRO,DESIGN])
    model=D('api-model','API, endpoint, SDK and contract','Distinguish a programming interface from its transport.',[
      ('The interface is the agreement','An API exposes operations and data to another program. A browser API can expose JavaScript objects; a library API can expose functions; a remote API can expose network operations. HTTP is a transport protocol and JSON a representation format. Neither defines the whole application contract.'),
      ('Endpoint and SDK','For this remote HTTP API, an operation is a method plus a route, such as GET /api/v1/tasks/{id}. The same path may support multiple operations. An SDK wraps calls in a language-specific interface; it still depends on the remote contract and introduces its own version and behavior.'),
      ('Contract ingredients','Record base URL, operations, input shapes, output shapes, errors, identity/access rules, limits and compatibility promises. Also explain semantics: what does complete a task mean, and who may do it? A schema cannot express every business invariant.')],
      'Label fetch(), GET /api/v1/tasks and a TasksClient.listTasks() wrapper.',
      'fetch is a browser/runtime API for requests; GET on the route is a remote operation; TasksClient is an SDK wrapper. Their interfaces sit at different layers.',[INTRO,THIRD,OAS])
    protocols=D('protocols','REST, RPC, GraphQL and event APIs','Choose an interface style for a use case.',[
      ('Resource and operation styles','Resource-oriented HTTP APIs expose identifiable resources and use HTTP semantics. REST is an architectural style with constraints including stateless interactions, caching and a uniform interface; a JSON CRUD service is not automatically a complete REST design. RPC centers named remote operations.'),
      ('Typed alternatives','GraphQL gives clients a typed field-selection/query model. gRPC commonly uses Protocol Buffers service definitions and generated clients, with unary and streaming calls. SOAP uses XML message conventions. Choose by consumer needs, tooling and operational constraints; no style is universally best.'),
      ('Events and live connections','A webhook sends a server-initiated HTTP notification to a receiver. Server-Sent Events streams server-to-client events; WebSocket supports messages in both directions. Authentication, reconnects, ordering and delivery guarantees remain application decisions.')],
      'Choose one approach for a public task catalog and one for a continuous two-way collaboration channel.',
      'A resource-oriented HTTP interface can suit the catalog. A WebSocket channel can suit bidirectional updates. The choice still needs a contract for access, events and reconnects; this exercise does not require implementing those systems.',[INTRO,'https://graphql.org/learn/','https://grpc.io/docs/what-is-grpc/introduction/',MDN+'Web/API/WebSockets_API'])
    read=D('read-contract','Read a real operation contract','Extract the information needed to make one call.',[
      ('A contract checklist','Before calling: locate the exact environment/base URL, method and path; required identity; path/query/header/body inputs; response media types; success/error statuses; limits and retry rules. Distinguish required from optional fields and absent from null.'),
      ('Our worked operation','GET /api/v1/tasks?limit=2 requires Authorization: Bearer demo-alice locally. It returns 200 JSON with items and nextCursor. Each item has id, title, status and version. limit is 1–3; nextCursor is either an opaque string or null. Unauthorized calls return 401 Problem Details.'),
      ('Evidence beats inference','Read practice/openapi.json and inspect a live result. Do not infer all accepted values from one sample response. If the documentation, schema and server disagree, record the discrepancy and test the intended behavior.')],
      'Find the POST /api/v1/tasks operation in practice/openapi.json. Identify its required body field, success status and Location response header.',
      'The request body requires title, a nonempty trimmed string bounded by the fixture’s validation rules. Creation returns 201, the Task representation and Location of the new task. The fixture chooses the owner from the caller, never from client-supplied owner data.',[OAS,GUIDE])
    consume=D('consume','Make and interpret an API call','Separate HTTP, parsing and application outcomes.',[
      ('A bounded first request','```js\nasync function listTasks() {\n  const response = await fetch("/api/v1/tasks?limit=2", {\n    headers: { Authorization: "Bearer demo-alice", Accept: "application/json" },\n    signal: AbortSignal.timeout(2000)\n  });\n  if (!response.ok) {\n    const problem = await response.json();\n    throw new Error(`${response.status}: ${problem.title}`);\n  }\n  return response.json();\n}\n```\n\nRun on the local practice origin. This minimal fixture-specific example assumes the documented JSON media types; a reusable client should check content type and handle malformed or bodyless responses.'),
      ('Three checks','An HTTP 401 is a response, not a fetch network rejection. Parsing can fail even after a 2xx response. Parsed values still need application validation. Treat status, representation and business outcome as separate evidence.'),
      ('Follow the contract','A DELETE returning 204 needs no JSON parse. A 202 means work was accepted, not completed. Read the final state or operation resource when the contract requires it. Capture a safe request ID when debugging.')],
      'Call /api/v1/tasks first without authorization and then with demo-alice. Compare status, media type and data.',
      'The unauthenticated request returns 401 with application/problem+json and a challenge. The authorized request returns 200 with application/json. fetch resolves for both HTTP responses.',[FETCH,MDN+'Web/API/Response'])
    browser=D('browser-boundaries','Browser, server and secret boundaries','Know which policies are specific to browser callers.',[
      ('What CORS decides','CORS controls whether a browser shares a cross-origin response with script. It is not user authorization and does not prevent a command-line client from reaching a service. JSON POSTs or Authorization can require a preflight. no-cors does not grant access to an otherwise blocked response.'),
      ('What can be secret','Code shipped to a browser is visible to its user. A developer API key intended to be confidential belongs in a trusted backend or approved provider flow, not a bundle. Public-client identifiers differ from secrets. Backend access still needs authorization, validation and abuse limits.'),
      ('Cookie and token decisions','Cookie-based sessions introduce sending rules and CSRF considerations. Bearer tokens introduce storage/leak/replay risks. Neither eliminates XSS or server-side authorization. Use provider guidance and a threat model; the fixture’s labels are not a production authentication implementation.')],
      'A curl call succeeds but browser JavaScript cannot read its result. Does that show the API has correctly authorized the caller?',
      'No. Investigate browser origin policy separately from caller access. A confidential provider secret must not be exposed merely to work around browser restrictions. The local fixture is same-origin and does not simulate cross-origin configuration.',[FETCH,THIRD])
    sdk=D('sdk-client','Build a small reusable client','Keep transport policy in one place.',[
      ('A useful boundary','Let a client adapter build URLs, attach approved credentials, enforce time budgets, parse known media types and translate documented errors. Keep business decisions in the application. Preserve actionable status/problem/request-ID evidence without logging tokens.'),
      ('SDK tradeoffs','Generated clients reduce repetitive model/operation code, but generator support and validation vary. Review nullability, dates, enum handling, pagination and retry defaults. A generated method cannot prove the server enforces access rules or that the client handles new enum values safely.'),
      ('Typed does not mean validated','Compile-time types disappear at runtime. Verify returned values where untrusted data crosses a boundary. Keep schema checks distinct from business checks, and test your adapter against representative success and error responses.')],
      'Propose three methods for a TasksClient and identify where pagination policy belongs.',
      'listTasks, createTask and updateTask can mirror operations. A list adapter may expose individual pages or an explicit iterator; document which it does, its bounds and its stop condition.',[OAS,DESIGN,FETCH])
    resources=D('resources','Model resources and workflows','Design around what a consumer needs to accomplish.',[
      ('Start with scenarios','Write a small consumer workflow before choosing route names: create a task, list my unfinished tasks, complete one. Decide resource identity, ownership, states and allowed transitions. Storage tables are implementation details; the public model should be stable and understandable.'),
      ('Names and relationships','Use consistent nouns for resources and stable identifiers. GET /tasks/{id} selects a task, while /tasks?status=open selects a collection representation. A task ID is identity, not permission. Avoid exposing internal storage layout just because it is easy to serialize.'),
      ('Guidelines are choices','Microsoft/Azure guidance supplies useful design examples and strong consistency policies within that platform. Its URL, version and operation conventions are organizational policies rather than universal REST rules. Define your own coherent conventions and explain deviations.')],
      'Design one route for listing tasks and one for reading a task, including who may see the results.',
      'GET /api/v1/tasks returns only the caller’s visible tasks; GET /api/v1/tasks/{id} returns a visible task or the documented denial/not-found result. Both require server-side policy, even if IDs are unpredictable.',[DESIGN,GUIDE])
    operations=D('operations','Define reads, writes and state transitions','Tie methods to meaning rather than database verbs.',[
      ('State the write promise','POST may create a task or process a command; PUT usually supplies a replacement representation under a chosen contract; PATCH applies a defined partial change. DELETE removes the target association/representation as documented. HTTP method names do not encode every domain action.'),
      ('Our narrow PATCH contract','The fixture supports application/json partial updates to title and status only. It is not JSON Patch or JSON Merge Patch. status is open or done. A body with owner, id, version or an unknown field fails validation; missing fields remain unchanged.'),
      ('Outcomes and replay','Creation returns 201 and Location. Successful fixture deletion returns 204. Repeating a successful DELETE may yield 404 while still preserving its intended absence. Repeating POST can create duplicates unless a separate deduplication contract applies.')],
      'Predict PATCH {"status":"done","owner":"bob"} on Alice’s task.',
      'It returns 422; owner is not a writable field. A server must not blindly assign client object fields to a stored object. The title/status allowlist and caller-derived ownership are contract decisions.',[GUIDE,OAS])
    data=D('data-contract','Define input and output data','Describe allowed values and who controls each field.',[
      ('Shape plus meaning','Specify names, types, bounds, enums, required fields, absent/null meaning and examples. Dates need an agreed representation/timezone; money needs an agreed unit/precision. A string labeled date is not automatically parsed or validated by every tool.'),
      ('Separate create, patch and read','TaskCreate requires title; TaskPatch permits title/status with at least one property; Task includes server-owned id and version. Reusing one writable schema for all three can expose fields the caller must never control. The fixture rejects unknown write fields.'),
      ('Compatibility consequences','An input allowlist protects writes. Tolerant reading of unknown response fields can aid compatible evolution, but closed enums, strict generated clients and read schemas can still break. Make these policies explicit and test consumers before changing contracts.')],
      'Classify a missing title, a null title and an extra owner property in TaskCreate.',
      'All fail this fixture’s create contract: title is required, must be a bounded nonempty string, and owner is not allowed. A different API could choose different rules; callers must follow its actual schema.',[OAS,DESIGN])
    pages=D('pagination','Filter and paginate predictably','Bound collection work and follow opaque continuation tokens.',[
      ('A page contract','The fixture accepts limit 1–3 and optional status=open or done. Responses contain items and nextCursor. A null cursor ends traversal. Every page is filtered by access policy before pagination; returning a global count can leak other users’ data.'),
      ('Opaque is not magic security','Pass nextCursor unchanged, encoded through URLSearchParams, with the same filter. The fixture validates cursor/filter consistency, but its encoding is inspectable and not cryptographically protected. Production cursors need the appropriate integrity, expiry and access checks. Access must be rechecked on each page.'),
      ('Offset and cursor tradeoffs','Offsets are simple but writes can shift positions and large offsets can cost work. Cursor designs can support efficient stable ordering but complicate arbitrary jumps. Specify ordering, mutation consistency and whether results form a snapshot. This fixture orders by ID and does not promise snapshot isolation.')],
      'List Alice’s tasks with limit=1; follow nextCursor until null. Then reuse a cursor with a different status filter.',
      'Each page contains only Alice’s tasks, and traversal ends at null. A mismatched filter/cursor returns 400. A cursor must not bypass ownership policy.',[GUIDE,DESIGN])
    errors=D('errors','Make errors usable','Give clients a stable failure contract.',[
      ('Different failure categories','Document malformed syntax, invalid values, missing identity, denied access, absent resources, conflicting writes, stale validators and throttling. Choose statuses according to semantics and avoid disguising every failure as 200. Error text alone is not a stable machine interface.'),
      ('Problem Details in practice','The fixture returns application/problem+json with type, title, status, detail and instance. Its status agrees with the HTTP response. types identify failure categories; clients should not branch on a localized sentence. Error detail must avoid stack traces, credentials and other users’ data.'),
      ('Actionable outcomes','422 points to a request correction; 412 asks for a fresh representation and conflict resolution; 429 asks for the documented wait/retry behavior. Not every 4xx/5xx is safe to retry. The fixture uses 404 for objects outside the caller’s visibility to avoid revealing their existence.')],
      'Compare missing credentials, invalid JSON, invalid title and an inaccessible task.',
      'The fixture returns 401, 400, 422 and 404 respectively, with distinct problem types. Missing identity differs from a valid caller who lacks a function scope (403).',[RFC9457,OAS])
    credentials=D('credentials','Credentials, scopes and sessions','Separate proving identity from permitting an action.',[
      ('Authentication and authorization','Authentication establishes the relevant identity/credential context. Authorization decides whether that context may perform an action on an object or field. A valid token, successful login or readable UI does not establish every permission.'),
      ('Key, bearer and JWT distinctions','An API key may identify an application or authorize access under a provider’s contract. A bearer credential can be used by whoever holds it. JWT is a token format, not proof that it is valid; servers must validate appropriate signature, issuer, audience, lifetime and policy. Do not treat decoded claims as trusted before validation.'),
      ('Teaching fixture','demo-alice and demo-bob allow task reads/writes for their respective owners. demo-readonly has Alice’s task-read scope but no writes. It is a fixed local mapping with no signing, token issuance or credential security. Real systems need validated identity infrastructure and secret handling.')],
      'Try GET and POST /api/v1/tasks with demo-readonly.',
      'GET succeeds for visible Alice-owned tasks. POST returns 403 because the caller lacks write scope. This is a function permission check, separate from object ownership.',[SEC+'0xa2-broken-authentication/',OAS])
    oauth=D('oauth','OAuth, OpenID Connect and delegated access','Understand the roles before configuring a provider.',[
      ('Distinct jobs','OAuth 2.0 describes delegated authorization; OpenID Connect adds an identity layer. Keep resource owner, client, authorization server and resource server separate. An access token is intended for the resource server; an ID token is intended for the client and is not a generic API access token.'),
      ('A modern flow outline','Authorization code with PKCE binds code redemption to the initiating client. Use a validated provider flow, correct redirect handling, CSRF protections and token validation. Current security guidance changes how older grant examples should be used; do not select a flow just because a tutorial is short.'),
      ('Application decisions remain','Scopes and audience constrain intended access but do not replace object-level policy. Confidential clients and public clients have different secret capabilities. Refresh tokens need deliberate storage/rotation/revocation controls. The local fixture does not implement OAuth; this lesson is a conceptual map.')],
      'A client has an ID token and wants to call a Tasks API. What must it check instead of simply sending that token?',
      'Use the provider’s appropriate API access token with the correct audience/scopes, then enforce object/action policy at the resource server. A login result alone does not grant access to arbitrary API objects.',[RFC9700,OAS])
    authz=D('authorization','Object, function and property access','Apply access policy at every relevant boundary.',[
      ('Three independent checks','Can this caller invoke the function? May it read/write this particular task? Which input/output fields may it control or see? These correspond to OWASP broken function, object and object-property authorization risks. A shared route or GUID cannot answer them.'),
      ('Enforce before mutation and output','Select visible resources using trusted identity and policy. Validate writable fields, and serialize only approved output fields. Check list, detail, update, delete and nested-resource operations; enforcing policy only on the detail view leaves other paths exposed.'),
      ('Test another caller','Alice should not read, modify or delete Bob’s task. A readonly identity should not create a task. A writable Alice request cannot change owner. Use explicit cross-user tests, not just unauthenticated requests.')],
      'Use demo-alice to GET /api/v1/tasks/t4, then try a body with owner=bob when creating a task.',
      'The fixture’s t4 belongs to Bob, so Alice sees 404. A client-selected owner field produces 422. Both tests matter even though Alice’s token itself is accepted.',[SEC+'0xa1-broken-object-level-authorization/',SEC+'0xa3-broken-object-property-level-authorization/',SEC+'0xa5-broken-function-level-authorization/'])
    validation=D('validation','Validate inputs and external dependencies','Treat inbound and outbound data as untrusted.',[
      ('Shape checks and business rules','Parse, validate shape/bounds/allowed fields, authorize, then enforce business invariants. Bound body sizes and expensive queries. Content-Type is a declaration, not proof of correct content. Reject or handle unknown fields according to the published contract.'),
      ('Server-side request forgery','A feature that fetches a caller-supplied URL can expose internal services or cloud metadata. Validate destination policies, account for redirects/DNS changes and enforce network controls and time budgets. Do not build a generic URL-fetch proxy for convenience.'),
      ('Unsafe API consumption','Upstream API data and callbacks need validation too. A trusted brand does not justify blindly using returned URLs, SQL fragments or HTML. Use bounded parsing, schema/business checks, least privilege and failure isolation at integration boundaries.')],
      'A task import endpoint accepts a remote URL and directly fetches it. Name two boundaries that need controls.',
      'The destination/redirect/network policy must prevent unsafe server-side requests; the returned representation needs size, type/schema and business validation. User authentication alone does not resolve either risk.',[SEC+'0xa7-server-side-request-forgery/',SEC+'0xaa-unsafe-consumption-of-apis/'])
    threats=D('threats','Complete OWASP API risk map','Connect all ten 2023 risks to concrete API controls.',[
      ('Identity and access risks','API1: object authorization; API2: authentication; API3: object-property authorization; API5: function authorization. Check trusted identity and per-action/object/field policy, limit exposed data and test cross-user behavior. These are distinct failures, not one generic login issue.'),
      ('Work and workflow risks','API4: unrestricted resource consumption; API6: unrestricted access to sensitive business flows. Bound payloads, query cost, concurrency and resource use; add controls appropriate to a valuable workflow such as booking or redemption. A rate limit alone may not stop business automation abuse.'),
      ('Environment and dependency risks','API7: SSRF; API8: security misconfiguration; API9: improper inventory management; API10: unsafe API consumption. Control outbound destinations, configure securely, track deployed versions/endpoints and validate upstream data. Retired endpoints and undocumented debug features still need ownership.'),
      ('A prioritization tool','The Top 10 is a starting point, not a complete security certification or universal risk ranking. Model your assets, callers, deployment and failure costs. Every risk has its full optional OWASP reference, including scenarios and prevention guidance.')],
      'Match an old untracked API version, a bulk query with no bound and client-controlled owner fields to the risk map.',
      'They illustrate API9 inventory, API4 resource consumption and API3 property authorization. Their actual impact depends on the service and its policies.',[SEC+'0x11-t10/'])
    openapi=D('openapi','Write an OpenAPI description','Make a machine-readable contract without mistaking it for enforcement.',[
      ('Root fields and operations','An OpenAPI document describes servers, info, paths/operations, inputs, responses, components and security requirements. info.version is your API release identifier; openapi names the specification version. operationId should identify an operation consistently for tools.'),
      ('Our complete artifact','practice/openapi.json describes the implemented local Tasks API. It uses OpenAPI 3.1.0, the 3.1 feature set, and a loopback server. The complete 3.1.2 specification is in the reference; 3.2.1 is optional newer-version reading. Check your toolchain before adopting a newer feature or dialect.'),
      ('Contract workflow','Design a consumer example, define the contract, review it, validate/lint it and test the implementation against it. Documentation generators, SDKs and mocks are useful outputs; they do not enforce server permissions or automatically cover business invariants.')],
      'Find servers, paths, components.schemas and components.securitySchemes in the example artifact. Identify which part actually protects the server.',
      'The artifact describes them; the server’s trusted identity/access code protects requests. A security scheme definition is not a running authentication implementation.',[OAS,'https://swagger.io/docs/specification/v3_0/about/'])
    schemas=D('schema-models','Schemas, parameters and examples','Model a 3.1 contract precisely.',[
      ('Input location matters','Path parameters are required; query/header inputs have their own serialization and requiredness. requestBody describes payload media types and its schema. responses describe outcomes, content and headers. Always define plausible failures, not just 200.'),
      ('3.0 and 3.1 are different','OpenAPI 3.1 aligns Schema Objects with JSON Schema 2020-12. A nullable string can use type: ["string", "null"]. Do not copy 3.0 nullable syntax into a 3.1 lesson without considering version semantics. required lists object properties; it does not mean non-null or nonempty by itself.'),
      ('Composition and validation','oneOf means exactly one matching schema; anyOf means at least one; allOf requires every schema and does not mean inheritance by itself. readOnly/writeOnly annotate direction but need implementation/tool support. Examples help humans but are not validation rules.')],
      'Check TaskCreate, TaskPatch and TaskPage in the supplied spec. Why are they separate?',
      'The create model requires title; patch is partial with at least one allowed property; a page has items and a nullable cursor. Distinct shapes express different operations and reduce accidental write exposure.',[OAS])
    refs=D('refs-security','Reuse components and describe security','Use references and requirements with the right semantics.',[
      ('References and reuse','Keep shared schemas, parameters, responses and security schemes in components, referenced with $ref. Resolve relative references using the correct base and test every target. A file containing reusable components does not automatically apply them to operations.'),
      ('Security alternatives','In the security array, separate requirement objects describe alternatives (OR); multiple schemes within one object combine requirements (AND). An empty security array on an operation removes an inherited requirement. Document intended scopes; actual enforcement belongs in the server.'),
      ('Beyond basic CRUD','OpenAPI also describes callbacks, webhooks, links, headers, examples and encoding. Operation responses need descriptions even when no body is returned. Consult the optional specification chapters rather than squeezing every object into the core course.')],
      'Explain security: [{"bearerAuth": []}] and the health operation’s security: [].',
      'The first requires the described bearer scheme under the contract. The health operation explicitly overrides inherited security and is public in the fixture. Neither setting implements token validation.',[OAS])
    docs=D('documentation','Publish documentation people can use','Document an integration, not only a list of routes.',[
      ('The human guide','Include purpose, environments/base URLs, quick start, credentials/access, operations, realistic examples, error recovery, limits, idempotency, pagination and version/support policy. Explain the workflow across calls. Generated endpoint pages are one part of this guide.'),
      ('Keep one contract source','Version the OpenAPI description with the implementation, examples and changelog. Render it through a compatible Swagger UI/Redoc or other tool if useful. Generated SDKs/collections must be reviewed and refreshed; independently edited copies drift.'),
      ('Examples are commitments','Run examples against a clean fixture in CI. Use synthetic credentials and data. Cover denied/invalid requests as well as success, and name the environment clearly. A beautiful documentation page with stale examples is still difficult to use.')],
      'Write a three-step quick start for the local Tasks API.',
      'Start the practice server; make an authenticated list request with demo-alice; create a title-only task and follow its Location. Then include the expected statuses and a link to the error/access contract.',[DESIGN,OAS])
    postman=D('postman','Explore and test with Postman','Use the supplied collection as a reproducible workflow.',[
      ('Import and configure','Import practice/tasks.postman_collection.json. baseUrl defaults to http://localhost:8000/api/v1 and token to demo-alice. Run the collection against a fresh practice server. It stores a created task ID and ETag for dependent requests; the runner needs the chosen order.'),
      ('Assertions beyond status','The supplied requests check statuses, key data fields, media types and state changes. A 200 alone cannot prove correct ownership or mutation. Post-response scripts use pm.test/pm.expect; keep failures named so they explain which promise broke.'),
      ('Local and shared values','Keep real secrets out of exported variables and shared collections. Demo token values are intentionally public. UI names and plan features change; consult the linked current Postman docs. The shipped Node test runner offers the same fixture practice without needing a Postman account.')],
      'Run the collection; identify the check that proves a second POST with the same key did not create a second task.',
      'The replay request checks the same created ID and the replay header, while a later list/state test can confirm no duplicate. A status-only check would not establish deduplication.',[POSTMAN,EXTERNAL_SOURCES[1]['url'],EXTERNAL_SOURCES[2]['url']])
    layers=D('test-layers','Unit, integration and contract tests','Choose tests according to the promise being checked.',[
      ('Different evidence','Unit tests isolate logic; integration tests exercise components together; contract/schema checks compare messages with declared shapes; end-to-end tests cover consumer workflows. A passing schema check cannot prove ownership isolation, performance or usability.'),
      ('Use a test matrix','Combine valid/invalid input, missing/valid/wrong identity, missing/other-owner objects, supported/unsupported operations, stale/fresh validators and successful/failing dependencies. Test exact state changes and sensitive fields, not only codes.'),
      ('Mocks are useful limits','Mocks help consumers work before a server exists and simulate failures, but can repeat a mistaken contract. Run real implementation checks too, and verify schema/reference validity, examples and backward compatibility in CI.')],
      'Place unknown-field rejection, Alice/Bob isolation and OpenAPI $ref resolution into an appropriate test layer.',
      'Shape/rule logic can have unit checks; cross-user requests need integration behavior tests; references/spec structure need contract validation. Some checks overlap to catch drift across layers.',[OAS,DESIGN,POSTMAN])
    negatives=D('negative-tests','Test denials, limits and drift','Make failure behavior a deliberate part of quality.',[
      ('A useful local matrix','Use demo-readonly for write denial, demo-alice on Bob’s t4 for object isolation, unknown fields for validation, an old If-Match for stale writes, and one repeated idempotency key with different input for a conflict. Assert that denied requests do not change state.'),
      ('Fixture controls','GET /api/v1/demo/rate-limit always returns a synthetic 429 with Retry-After. GET /api/v1/demo/slow is delayed. These deterministic examples do not implement a production quota system or simulate every failure. Reset by restarting or create isolated servers in tests.'),
      ('Prevent silent drift','Validate the description and messages in CI; compare expected business outcomes and safe output fields. A specification can be valid while its server disagrees, and a server can work while its docs are stale. Both sides need evidence.')],
      'Run node scripts/test-api.cjs. Explain why the suite uses a fresh server instance.',
      'Isolated memory state keeps IDs, ownership, validators and deduplication tests reproducible. It avoids dependencies on earlier manual requests and exposes unintended state changes.',[OAS,SEC+'0xa1-broken-object-level-authorization/'])
    retry=D('retry','Timeouts, retries and idempotency','Retry according to the operation contract and uncertainty.',[
      ('A time budget','Bound the overall operation, attempts and response size. A timeout/abort can stop the client waiting without undoing an accepted server write. Retry transient failures with bounded backoff/jitter where allowed; do not automatically retry every response.'),
      ('Our explicit POST contract','An optional Idempotency-Key on task creation deduplicates the same semantic input for the same caller. Within ten minutes and the bounded in-memory cache, the same key/body replays the original 201 and ID; a different body returns 409. Restart clears the cache. This is a teaching contract, not a universal HTTP guarantee.'),
      ('Choose the evidence','Read Retry-After where relevant, consider method safety and application effects, and keep the key stable across retries of the same intended creation. Changing the key on each retry defeats deduplication. Define retention, scope, conflicts and failure/unknown-outcome recovery explicitly.')],
      'Create a task twice with key lesson-create-1 and the same title, then change the title while keeping the key.',
      'The second request replays the same task ID; the changed semantic input returns 409. A production service needs durable/atomic deduplication and a documented expiry policy.',[GUIDE,FETCH])
    concurrency=D('concurrency','Prevent lost updates with validators','Detect stale client writes rather than silently overwriting.',[
      ('The overwrite problem','Two clients read version 1, then both change the task. Without a condition, a later write can overwrite an earlier decision. A version/validator lets the server reject a write based on stale knowledge; the caller still needs a conflict resolution policy.'),
      ('Our conditional update','GET /tasks/{id} returns an ETag. PATCH requires the current exact ETag in If-Match; missing returns 428 and stale returns 412. A successful write increments version and returns a new validator. The fixture supports this single-validator contract, not every generic conditional-header variant.'),
      ('Conditional reads','If-None-Match can revalidate a saved representation. A matching fixture GET returns bodyless 304; keep the cached data. If-Match on a write and If-None-Match on a read serve different purposes.')],
      'Read t1 twice, patch it using the first validator, then try a second patch with the old validator.',
      'The first succeeds and advances version; the second returns 412 and does not mutate the task. Fetch the current state and decide how to merge or ask the user. Blindly retrying with a new validator can discard another change.',[GUIDE,OAS])
    asyncops=D('async-webhooks','Long-running work and webhooks','Separate acceptance, completion and delivery.',[
      ('Operation resources','POST /api/v1/exports accepts work and returns 202 with Location of /operations/{id}. Follow it until state succeeds or fails under a documented wait/budget policy. The fixture completes a synthetic export after a short delay; acceptance is not the completed result.'),
      ('Webhook delivery contract','Define event identity, schema/version, receiver verification, replay controls, acknowledgment, retries and duplicate handling. Verify signatures against the exact bytes according to the provider’s scheme. A random ID alone does not establish sender identity.'),
      ('Ordering and durability','Delivery can be duplicated or delayed; define ordering guarantees rather than assuming them. A receiver can verify/authorize, durably record/enqueue, acknowledge and process idempotently. A scheduled export job and a webhook are alternatives/complements with different operating costs. Webhook delivery is conceptual here, not implemented by the fixture.')],
      'Start an export and immediately read its operation resource. Does the first 202 prove that its artifact is ready?',
      'No. Poll the operation state within a bound; this fixture moves from running to succeeded. A real contract must also explain failure/cancellation, retention and authorized access to the result.',[GUIDE,OAS])
    streams=D('streams','Streaming contracts and backpressure','Know when request–response pages are insufficient.',[
      ('Two directions','SSE carries server-to-client event streams over HTTP; WebSocket supports bidirectional messages on a connection. gRPC has streaming call patterns too. None removes the need for identity, schema/version and resource limits.'),
      ('A live-data contract','Specify event type/ID, reconnection, resume behavior, duplicates, ordering, retention and what a slow consumer should do. Backpressure and bounded queues prevent a slow client from consuming unlimited memory. Connection success is not proof that every message is accepted or delivered.'),
      ('Pick the smaller commitment','A paginated polling API may be simpler for occasional updates. Choose streaming for a concrete latency/traffic need and account for gateways and client support. The course supplies conceptual design practice and full MDN references; it does not add a second live messaging backend.')],
      'Design reconnection behavior for a dashboard that may disconnect for ten minutes.',
      'Define whether it can resume by event ID or must refresh a current snapshot, how long events are retained, and how it ignores duplicates. Without an explicit contract, reconnecting is guesswork.',[MDN+'Web/API/WebSockets_API',MDN+'Web/API/Server-sent_events/Using_server-sent_events'])
    versioning=D('versioning','Evolve and retire APIs deliberately','Assess changes from the consumer’s perspective.',[
      ('Compatibility is broader than syntax','Removing a field/operation or making an optional input required can break consumers. New enum values, changed ordering, tighter limits, new authorization requirements or altered latency can also break behavior. Adding a field is not automatically harmless to every strict client.'),
      ('A migration plan','Inventory callers, specify a version/support policy, add a compatible alternative, document deprecation, provide examples/telemetry and agree a retirement timeline. Versioning through path, query/header or negotiation has tradeoffs; Azure’s date-based policies are platform conventions, not universal requirements.'),
      ('Keep artifacts together','Review server, OpenAPI, docs, SDKs and collection examples as one change. Preserve older versions only with explicit ownership/security maintenance; untracked legacy endpoints are an API inventory risk.')],
      'A task API adds archived to a previously closed open/done enum. Classify the change.',
      'It can break exhaustive clients or validators, even if the JSON remains valid. Review the compatibility promise, update consumers/schema/tests and plan versioning or an agreed extensible-enum policy.',[DESIGN,'https://github.com/microsoft/api-guidelines/blob/a7022a299442a8352431874e63ec4dff548a1b81/azure/VersioningGuidelines.md',SEC+'0xa9-improper-inventory-management/'])
    observe=D('observability','Operate an API you can diagnose','Connect requests to useful, safe operational evidence.',[
      ('Measure outcomes','Track request count, latency percentiles, errors by route/status, saturation, quota denials and relevant business outcomes. Define service objectives and budgets. A good average can hide a slow tail or one failing tenant.'),
      ('Trace without leaking','Use request/correlation IDs and structured safe logs. Avoid credentials, sensitive payloads and unbounded identifiers in metric labels. The fixture returns X-Request-Id for debugging; it is not a full tracing or monitoring system.'),
      ('Configuration and inventory','Track environment URLs, deployed versions, owners, access policy and dependency timeouts. Protect administrative/debug endpoints, separate environments and roll back deliberately. A secret committed to documentation is still exposed, even if the API uses TLS.')],
      'Choose evidence for a user reporting intermittent task creation failures without logging their bearer token.',
      'Correlate the safe request ID, route/status, timing, relevant dependency result and deduplication outcome. Confirm whether a write succeeded before asking the caller to repeat an ambiguous operation.',[GUIDE,SEC+'0xa8-security-misconfiguration/',SEC+'0xa9-improper-inventory-management/'])
    capstone=D('capstone','Capstone — review the Tasks API','Demonstrate an integration from contract to evidence.',[
      ('Run the workflow','Start a fresh server. List Alice’s tasks through all pages; create a title-only task with an idempotency key; follow Location; repeat creation; read and update with If-Match; test a stale update; delete and confirm absence. Start and poll a synthetic export.'),
      ('Show boundary evidence','Include missing identity, readonly write denial, cross-owner denial and rejected server-owned fields. Explain their different failure categories. Import/run the Postman collection or use Node/curl; inspect practice/openapi.json alongside responses.'),
      ('Review the whole contract','Write a compact quick start, a request/response/error matrix, a pagination/retry policy and one backward-compatibility proposal. Separate what the contract states, what the fixture demonstrates and what a production deployment would still need.'),
      ('Completion criteria','Keep status/header/body/state evidence for every step. Identify how all ten OWASP API risks would matter to an expanded service. Finish the module check and final assessment. Optional reference reading is never a gate for core completion.')],
      'Propose one improvement and the tests needed to support it. Example: durable deduplication across server restarts.',
      'Specify key scope/expiry, atomic storage of outcome and concurrent/restart behavior. Add replay, changed-input, concurrency and crash/restart tests. A database alone does not establish the intended contract.',[OAS,DESIGN,SEC+'0x11-t10/'])
    modules=[
      S('m1','01 API foundations',[start,model,protocols,read],[
        ('Which defines a remote API operation here?',['A JSON object alone','A method, target and application contract','An HTTP header name'],1,'Operations include transport and application meaning.'),
        ('What is an SDK?',['A language-facing wrapper around interface operations','A replacement for all authorization','A particular HTTP status'],0,'An SDK helps callers use an API while depending on its contract.'),
        ('Does JSON CRUD automatically establish all REST constraints?',['Yes','Only with HTTPS','No'],2,'REST is an architectural style with additional constraints.'),
        ('What should you read before a new API call?',['Only the endpoint URL','Only a sample success body','Inputs, outcomes, access and operational rules'],2,'The contract includes more than a route.')],'Foundations'),
      S('m2','02 Consume APIs',[consume,browser,sdk],[
        ('A fetch call receives HTTP 401. What usually happened?',['The server returned an HTTP response','fetch necessarily rejected as a DNS error','The response must be 200'],0,'HTTP error statuses still produce responses.'),
        ('Can browser-shipped code safely hide a confidential provider secret?',['Always','No','Only by minifying'],1,'The user can inspect code and values delivered to their browser.'),
        ('What does CORS replace?',['Object authorization','Token validation','Neither'],2,'Browser response-sharing policy is a separate boundary.'),
        ('What can a generated SDK still need?',['No tests','Runtime validation and reviewed behavior','No version tracking'],1,'Generation cannot prove implementation or business correctness.')],'Consumption'),
      S('m3','03 Design the contract',[resources,operations,data,pages,errors],[
        ('Why separate create and read schemas?',['To control writable versus server-owned fields','To make every field nullable','To remove all validation'],0,'Different operation directions have different contracts.'),
        ('How should a caller use nextCursor?',['Decode and increment its internals','Pass it unchanged under the same query contract','Treat it as authorization'],1,'Opaque continuation tokens do not replace access checks.'),
        ('Can a DELETE return 204 in this fixture?',['Only with a JSON body','Never','Yes, without parsing JSON afterward'],2,'204 is bodyless.'),
        ('What is a useful machine-facing error identifier?',['Localized detail text only','The documented problem type','An internal stack trace'],1,'Stable categories support recovery without text matching.')],'Design'),
      S('m4','04 Identity and API security',[credentials,oauth,authz,validation,threats],[
        ('Does a valid token authorize every object ID?',['Yes','No','Only when IDs are UUIDs'],1,'Object access policy still applies.'),
        ('Which caller token is intended for an API resource server?',['An appropriate access token','Any ID token','An unchecked decoded claim'],0,'Audience, scope, validation and policy matter.'),
        ('A server accepts client-controlled owner fields blindly. Which risk fits?',['Only DNS failure','Only caching','Object-property authorization failure'],2,'Property allowlists and access policy protect server-owned fields.'),
        ('Which risk includes untracked old API deployments?',['API9 improper inventory management','API1 by definition only','No API risk'],0,'Every deployed version needs ownership and controls.')],'Security'),
      S('m5','05 OpenAPI and documentation',[openapi,schemas,refs,docs],[
        ('Does an OpenAPI security scheme enforce server authentication?',['Yes','No','Only if rendered in Swagger UI'],1,'The description states a requirement; the server implements it.'),
        ('What does required: [title] alone guarantee?',['The property must be present','The value must be nonempty','The value cannot be null under any schema'],0,'Type/nullability/bounds are separate constraints.'),
        ('Separate objects in an OpenAPI security array mean what?',['AND always','No access requirement','Alternative requirements (OR)'],2,'Schemes within one requirement object combine; objects are alternatives.'),
        ('Which version identifier names the specification format?',['info.version','openapi','operationId'],1,'info.version identifies the described API version.')],'Contracts'),
      S('m6','06 Test API behavior',[postman,layers,negatives],[
        ('Which assertion adds evidence beyond a 201 status?',['The created ID and intended state are correct','The response is quick once','The route string contains tasks'],0,'Verify the outcome and access-sensitive representation.'),
        ('Does a schema-valid response prove cross-user isolation?',['Yes','Only with JSON','No'],2,'Authorization is a behavioral/business promise.'),
        ('Why use a fresh fixture for tests?',['To suppress errors','To control starting state and reproducibility','To avoid assertions'],1,'Isolation prevents dependence on earlier manual work.'),
        ('What should a denied write test confirm?',['Only a label in the UI','No unintended state mutation','That credentials were logged'],1,'Rejection and state preservation both matter.')],'Testing'),
      S('m7','07 Reliable integrations',[retry,concurrency,asyncops,streams],[
        ('A timed-out POST might have succeeded. What follows?',['The write was automatically rolled back','Investigate/retry using the documented deduplication contract','Always create a new key'],1,'Client waiting and server effects are separate.'),
        ('A stale If-Match in this fixture returns what?',['412 without mutation','200 with silent overwrite','304 with a write body'],0,'The write condition prevents a lost update.'),
        ('What does 202 establish?',['The final artifact is ready','The webhook was delivered exactly once','Work was accepted'],2,'Completion requires the defined status/result workflow.'),
        ('What must a streaming contract define?',['Only a socket URL','Reconnection, delivery and resource bounds','No schema'],1,'A live connection alone does not define reliable message behavior.')],'Reliability'),
      S('m8','08 Evolution and capstone',[versioning,observe,capstone],[
        ('Can a new enum value break an existing consumer?',['Yes','Never','Only when HTTP changes'],0,'Exhaustive handling and strict validators can fail.'),
        ('What belongs with a public version change?',['Only a new route','Contract, docs, clients/tests and migration/support policy','No communication'],1,'Compatibility and retirement need an integrated plan.'),
        ('Which is useful safe debugging evidence?',['A raw bearer token','Every private response field','A request ID with route/status/timing'],2,'Correlate behavior without exposing secrets.'),
        ('Does the fixture provide production OAuth and durable storage?',['Yes','No','Only on GitHub Pages'],1,'It deliberately demonstrates contracts with synthetic in-memory behavior.')],'Lifecycle'),
    ]
    final=[
      ('Which combination best describes the API contract?',['Operations, input/output meaning, access, errors and promises','Only JSON grammar','Only an HTTPS URL'],0,'The application agreement spans multiple concerns.'),
      ('An HTTP response is 200 but its declared JSON cannot parse. Which layer failed?',['DNS necessarily','Representation parsing','Authorization necessarily'],1,'Status and parsing are independent evidence.'),
      ('Where should a confidential upstream secret live?',['In a minified browser bundle','In a URL fragment sent to every user','In an appropriate trusted environment/provider flow'],2,'Code delivered to a browser cannot hide a confidential secret.'),
      ('Which fixture body is a valid task creation?',['{"title":"Read the contract"}','{"owner":"bob"}','{"title":null}'],0,'Creation accepts the writable title field, not owner or null.'),
      ('Alice knows Bob’s task ID. What should the server do?',['Authorize by object/action policy','Return it because the ID is correct','Trust the hidden UI'],0,'Knowing an identifier does not confer permission.'),
      ('Why can a readonly caller read but not create?',['A parser forbids every POST globally','Its function scope does not grant write access','CORS is its sole identity'],1,'Function permission differs from object ownership.'),
      ('What does a JWT-shaped string establish by itself?',['A validated audience','Unrestricted authorization','Neither identity validation nor authorization'],2,'Token formatting is not proof of trust.'),
      ('How should an API caller handle nextCursor?',['Invent the next encoded ID','Pass it under the documented filter/ordering contract','Use it as the bearer token'],1,'The server must validate continuation and access.'),
      ('A problem response has status 422. What must the origin’s HTTP status be if it includes that member?',['422','200 always','Any unrelated code'],0,'The origin’s status member agrees with its HTTP status.'),
      ('Which artifact is the machine-readable HTTP API description?',['A screenshot','An OpenAPI document','A bearer token'],1,'The description defines operations, messages and security requirements.'),
      ('Does readOnly in a schema alone block a server mutation?',['No; tool/implementation enforcement matters','Yes, all servers enforce it automatically','Only in a static page'],0,'Annotations are not a substitute for access/validation logic.'),
      ('What does oneOf require?',['At least one with no limit','Every schema','Exactly one matching schema'],2,'Composition keywords have different validation meanings.'),
      ('What should an authorization denial test also assert?',['That nothing unauthorized changed or leaked','That a CSS class is green','That the token appears in logs'],0,'Business outcomes and exposure matter beyond status.'),
      ('Same caller/key, different semantic POST input in the fixture returns what?',['A second independent creation','409 conflict','200 silently changing the cached input'],1,'The key cannot represent two different intended creations.'),
      ('After a successful PATCH, an old validator is reused. What is the right fixture outcome?',['A lost update','A body-bearing 304','412 and preserved state'],2,'A stale write must not overwrite newer data.'),
      ('Which statement about an abort is sound?',['It always cancels server side effects','It can end client waiting while a write outcome remains uncertain','It always proves a 404'],1,'Cancellation and committed effects are separate.'),
      ('A webhook arrives twice. What should a receiver’s contract plan include?',['Deduplication/idempotent processing with verified sender context','Assume the second is impossible','Blindly repeat every irreversible action'],0,'Duplicate delivery and replay need explicit handling.'),
      ('Which change needs consumer compatibility review?',['Only removing an entire server','Only changing JSON indentation','A new value in a formerly closed response enum'],2,'Valid JSON can still break a consumer’s assumptions.'),
      ('Why are API inventory and ownership useful?',['They make authentication unnecessary','They identify deployed/retired surfaces needing maintenance and controls','They replace HTTP routing'],1,'Forgotten versions/debug endpoints still expose risk.'),
      ('What demonstrates a capstone claim most strongly?',['A request/response/header/state trace plus contract and boundary tests','Only a success screenshot','Only an imported OpenAPI file'],0,'Combine contract, behavior and negative evidence.')]
    return dict(schemaVersion=1,id='api-documentation-course-v1',title='API',description='Learn API consumption, design, contracts, security, testing and reliable integrations, with a concise core path and an optional curated source collection.',sections=modules,settings=dict(passScore=80,allowRetakes=True,showLessonDetails=False,unlockAll=True,sequential=False,requireLessons=True,brand='#98cdb1',background='#0c0e12',surface='#14171d',text='#edf0f7',muted='#b4bac9',border='#343b49',fontScale=1,spacing=24,contentWidth=1000,radius=8,font='system',headingFont='system',lineHeight=1.65),finalQuiz=Q('api-final','Final assessment — API skills','API integration',final))
